name: Dream Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          ADD_LABEL: "good to go"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
